version: '3.3'

services:
  web:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .flask.env
    image: mia:latest
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - "mia-db:mia"

  database:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .sql.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24