version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mia:latest
    ports:
      - "5000:5000"
    expose:
      - "5000"
    links:
      - "mia-db:mia"

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mia'
      MYSQL_PASSWORD: 'Howdy1234'
      MYSQL_ROOT_PASSWORD: 'r00tp455w0rd'
    # env_file:
    #   - environmentfile.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24