version: '3.3'

services:
  db:
    container_name: mia-mysql
    image: mysql:8.0
    restart: always
    env_file: .sql.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24